const entries = [
  {
    word: "Love",
    pos: "noun, verb",
    pron: "lʌv",
    cat: "I",
    catLabel: "Relational Structures & Labels",
    isNew: false,
    brief: "The most universally claimed and least universally defined concept in human experience. Everyone is certain they know what it means. No two people mean the same thing.",
    origins: "Old English lufu, from Proto-Germanic *lubō. Where English has one word, ancient Greek had nine: eros (passionate desire), philia (deep friendship), storge (familial affection), agape (unconditional love), pragma (enduring commitment), ludus (playful affection), mania (obsessive attachment), philautia (self-love), and xenia (hospitality). The reduction to one word is not a simplification. It is an erasure of an entire taxonomy.",
    practice: "Most relational conflict attributed to 'love' is actually a mismatch of which kind of love two people are talking about. One person means eros; the other means pragma. Both say 'I love you.' Neither knows the conversation has already failed. Fromm argued in The Art of Loving (1956) that love is not a feeling but a practice — requiring care, responsibility, respect, and knowledge. Pop culture disagrees with him and this is most of the problem.",
    complicated: "The love languages framework (Chapman) is Fromm made accessible and partially stripped of rigor. The Chinese concept of ai (愛) is demonstrated through action rather than declaration — 'did you eat yet?' as an expression of love that has no obvious English translation. The single word 'love' does not have room for this.",
    alsoSee: ["Limerence", "Desire", "Romantic", "Attachment"]
  },
  {
    word: "Desire",
    pos: "noun, verb",
    pron: "dɪˈzʌɪə",
    cat: "II",
    catLabel: "Experiential & Phenomenological",
    isNew: false,
    brief: "What you want when you want it — except most people's desire doesn't work the way they've been told it should, and they spend years concluding something is wrong with them.",
    origins: "From Latin desiderare, possibly from de- (down from) + sidus (star) — a longing for what has fallen from the stars. The etymology already understands absence as its structure.",
    practice: "Rosemary Basson's responsive desire model (2000) is the most clinically significant piece of information most people never encounter outside a therapist's office. The dominant cultural narrative assumes desire arrives spontaneously. Basson's research found that for many people, desire is responsive: it emerges in response to arousal, not before it. Waiting to feel desire before engaging with a partner is, for this profile, waiting for something that arrives after the thing you're waiting for.",
    complicated: "The spontaneous/responsive distinction has been widely adopted in clinical sex therapy and almost entirely absent from popular discourse. The result is that an enormous number of people have concluded they have a desire problem when they have a desire model mismatch.",
    alsoSee: ["Limerence", "Erotic", "Basson's Model"]
  },
  {
    word: "Consent",
    pos: "noun, verb",
    pron: "ˈkɒnsɛnt",
    cat: "III",
    catLabel: "Practices & Philosophies",
    isNew: true,
    brief: "The minimum viable condition for ethical sex, consistently mistaken for the whole thing.",
    origins: "From Latin consentire — con (together) + sentire (to feel). To feel together. The legal and cultural evolution has stripped the etymology almost entirely: consent in practice has become a yes/no transaction rather than a mutual orientation.",
    practice: "The enthusiastic consent framework expands the binary into ongoing, affirmative, reversible engagement. You can consent at 9pm and withdraw at 10pm. Consent as culture — the idea that it is an ongoing relational practice rather than a single moment of permission — is where the conversation is going and largely hasn't arrived yet in mainstream discourse.",
    complicated: "The transactional model of consent is better than what preceded it and significantly worse than what's needed. BDSM communities have in many respects more sophisticated consent cultures than mainstream discourse — an irony that gets buried.",
    alsoSee: ["Kink", "Boundaries", "Enthusiastic Consent"]
  },
  {
    word: "Limerence",
    pos: "noun",
    pron: "ˈlɪm.ər.əns",
    cat: "II",
    catLabel: "Experiential & Phenomenological",
    isNew: true,
    brief: "The obsessive early attachment state most people spend their entire lives calling love. It is not love. It has a neurochemical lifespan. It ends.",
    origins: "Coined by psychologist Dorothy Tennov in 1979 in Love and Limerence: The Experience of Being in Love. Tennov invented the word because no existing term captured the involuntary, intrusive, obsessive quality of the state.",
    practice: "Limerence is characterized by intrusive thinking about the limerent object, acute sensitivity to their responses, intense fear of rejection. It typically lasts 18 months to three years. The neurochemical profile resembles OCD. When it ends — as it always does — many people mistake the ending for the relationship failing, rather than recognizing that the relationship is now beginning.",
    complicated: "Limerence and love are frequently confused because limerence feels more intense than most love experiences. The distinction matters enormously for relationship decision-making: commitments made during limerence are made under neurological conditions that do not persist.",
    alsoSee: ["Love", "Attachment", "Desire", "Parasocial Relationship"]
  },
  {
    word: "Erotic",
    pos: "adjective, noun",
    pron: "ɪˈrɒtɪk",
    cat: "II",
    catLabel: "Experiential & Phenomenological",
    isNew: false,
    brief: "Not what pornography is. Not simply what is sexually arousing. Something older, more embodied, and far more politically significant than either.",
    origins: "From Greek eros — the god of love and desire. Eros in Plato's Symposium is not merely sexual: it is the engine of all creation, the longing that moves humans toward beauty, truth, and the good.",
    practice: "Audre Lorde's 1978 essay 'Uses of the Erotic: The Erotic as Power' is the most important text most people have never read. Lorde argues that the erotic is a deep knowledge of the self, a capacity for feeling in its fullest sense. To suppress the erotic is to suppress self-knowledge.",
    complicated: "The erotic/pornographic distinction is one Lorde draws sharply: pornography is sensation without feeling, the erotic is feeling embodied. The distinction is not about content but about the relationship of the person to the experience.",
    alsoSee: ["Desire", "Sensual", "Pornography"]
  },
  {
    word: "Hysteria",
    pos: "noun",
    pron: "hɪˈstɪəriə",
    cat: "V",
    catLabel: "Historical & Theoretical",
    isNew: false,
    brief: "A diagnosis invented to medicalize inconvenient female behavior. The organizing question it raises has never been answered: who gets to be a sexual being, and who decides?",
    origins: "From Greek hystera — uterus. The ancient Greeks believed an unsatisfied, 'wandering' uterus caused irrational behavior in women. The diagnosis persisted in Western medicine until 1980. The treatment for centuries was 'pelvic massage' administered by physicians — which is to say, externally-induced orgasm, not named as such.",
    practice: "The hysteria throughline is the conceptual anchor for understanding how medical authority has been used to regulate female sexuality across time. The pattern is consistent: female sexual experience that doesn't serve patriarchal structures gets classified as pathology. What changes is the vocabulary.",
    complicated: "The line from hysteria to contemporary sex tech is direct and underexamined. Vibrators were invented as medical instruments for administering the 'treatment' for hysteria at scale. The technology did not change the politics; it changed the ownership.",
    alsoSee: ["Medicalization", "Basson's Model", "Orgasm Gap", "Sex Tech"]
  },
  {
    word: "Kink",
    pos: "noun",
    pron: "kɪŋk",
    cat: "III",
    catLabel: "Practices & Philosophies",
    isNew: false,
    brief: "Sexual interests outside what is statistically common — which includes more people than will ever admit it in polite company.",
    origins: "From Dutch kink — a twist in a rope. The clinical literature prefers 'paraphilia' (from Greek para, beyond, + philia, attraction) — but paraphilia carries a pathologizing history that kink communities have largely rejected.",
    practice: "Studies consistently show that people who engage in consensual BDSM and kink practices tend to have better communication skills and higher relationship satisfaction than the general population. This finding receives almost no popular coverage.",
    complicated: "The DSM distinguishes between paraphilias (unusual interests) and paraphilic disorders (interests that cause harm or distress) — a distinction that matters and often gets lost.",
    alsoSee: ["BDSM", "Consent", "Paraphilia"]
  },
  {
    word: "Romantic",
    pos: "adjective",
    pron: "rəʊˈmantɪk",
    cat: "I",
    catLabel: "Relational Structures & Labels",
    isNew: false,
    brief: "Not a synonym for loving or intimate. A specific cultural inheritance from medieval troubadours who wrote about longing, suffering, and adultery — and somehow this became the template for healthy partnership.",
    origins: "From the troubadour tradition of 11th–13th century Occitania: courtly love poetry celebrating desire for an unattainable beloved, typically someone else's spouse. The genre was built on impossibility and longing. It was not designed as a model for stable partnership.",
    practice: "The romantic/erotic/intimate distinction is one most people haven't consciously made. Romantic refers to a cultural script of pursuit, gesture, and longing. Erotic refers to embodied desire. Intimate refers to mutual self-disclosure. A relationship can be deeply intimate without being particularly romantic.",
    complicated: "Romantic love as the basis for long-term partnership is historically very recent — roughly 200 years old in mainstream Western culture. The expectation that one person will be simultaneously your romantic ideal, erotic partner, best friend, co-parent, and financial partner across 50+ years is, historically speaking, an experiment. The results are mixed.",
    alsoSee: ["Love", "Erotic", "Intimacy", "Limerence"]
  },
  {
    word: "Intimacy",
    pos: "noun",
    pron: "ˈɪntɪməsi",
    cat: "I",
    catLabel: "Relational Structures & Labels",
    isNew: false,
    brief: "The experience of being known — not seen, not desired, not admired. Known. Most people are terrified of it and spend considerable energy pursuing its simulacra instead.",
    origins: "From Latin intimus — innermost, superlative of inter (within). Not surface, not performance, not even affection — the place underneath all of that.",
    practice: "The capacity for intimacy requires a stable enough sense of self to risk real self-disclosure. Schnarch's differentiation model argues that most people achieve pseudo-intimacy: the feeling of closeness without the actual risk of being known.",
    complicated: "AI companionship raises the question acutely: can intimacy exist with an entity that cannot be changed by you? The Chinese concept of xīn (心), the heart-mind as a unified organ, suggests that true knowing changes you.",
    alsoSee: ["Vulnerability", "Differentiation", "Parasocial Relationship"]
  },
  {
    word: "Tantra",
    pos: "noun",
    pron: "ˈtantrə",
    cat: "III",
    catLabel: "Practices & Philosophies",
    isNew: false,
    brief: "Three completely different things currently sharing one word, and the gap between them is not a minor detail.",
    origins: "From Sanskrit tantra — loom, weave, system. Traditional Tantra is a Hindu and Buddhist ritual tradition dating to approximately the 5th century CE. It was never principally about sex. Western practitioners encountered it in the 19th century and found the sexual elements more interesting than the rest.",
    practice: "The three versions: Traditional Tantra (complex ritual systems; sexuality is one small element); Neo-Tantra (1960s–70s Western repackaging that extracted the sexual elements); Pop Tantra (slow sex, prolonged arousal, spiritual connection — what most people currently mean). All three are real. Almost nobody names which one they mean.",
    complicated: "The commercialization of Tantra in the wellness space has created a landscape where the word primarily functions as branding. This does not make the practices invalid; it makes the vocabulary unreliable.",
    alsoSee: ["Somatic Work", "Kink", "Erotic"]
  },
  {
    word: "Vulva",
    pos: "noun",
    pron: "ˈvʌlvə",
    cat: "IV",
    catLabel: "Anatomy & Physiology",
    isNew: false,
    brief: "The external genitalia of people with this anatomy. Not the vagina. The two words refer to different structures. The confusion has measurable consequences for health communication.",
    origins: "From Latin vulva — womb, covering. The vagina, from Latin vagina — sheath, scabbard — refers to the internal canal. Two distinct anatomical structures with two distinct names, one of which is systematically used to refer to both.",
    practice: "The cultural default of 'vagina' to refer to all female genitalia means that most people with vulvas grew up without an accurate word for their own external anatomy. You cannot advocate for your own health using inaccurate vocabulary.",
    complicated: "The misuse is so pervasive that correcting it reads as pedantic. It is not pedantic — it is a literacy issue with real medical stakes. The same imprecision does not exist for the analogous structures in male anatomy. The asymmetry is not coincidental.",
    alsoSee: ["Clitoris", "Body Literacy", "Orgasm Gap"]
  },
  {
    word: "Clitoris",
    pos: "noun",
    pron: "ˈklɪtərɪs",
    cat: "IV",
    catLabel: "Anatomy & Physiology",
    isNew: false,
    brief: "An organ that exists entirely for pleasure, whose full structure was not accurately mapped until 1998. Medicine had other priorities.",
    origins: "From Greek kleitoris. Known to anatomists since the 16th century but consistently misrepresented or ignored. The full internal structure was not documented with MRI imaging until Helen O'Connell's 1998 research.",
    practice: "The clitoris is the only human organ whose sole documented function is pleasure. The internal structure means that 'internal' orgasms are, in many cases, clitoral orgasms reached through internal stimulation — a reframe that resolves decades of confusion about vaginal vs. clitoral orgasm as a binary.",
    complicated: "The question of why accurate clitoral anatomy took until 1998 is more interesting than the answer. O'Connell's paper was not controversial — it was simply new information that the field should have had centuries earlier.",
    alsoSee: ["Vulva", "Orgasm Gap", "Body Literacy"]
  },
  {
    word: "Dating",
    pos: "noun, verb",
    pron: "ˈdeɪtɪŋ",
    cat: "I",
    catLabel: "Relational Structures & Labels",
    isNew: false,
    brief: "A word everyone uses and almost no one defines. Two people can be 'dating' for months while holding entirely different models of what that means.",
    origins: "A distinctly 20th-century American concept. Before the early 1900s, courtship happened in the home under parental supervision. The shift to public commercial courtship spaces created the need for new vocabulary. 'Dating' is barely 120 years old.",
    practice: "The contemporary meaning of 'dating' contains no agreed-upon status. Are you exclusive? Are you still on apps? 'We're dating' answers none of these questions, and every person in the room has a different assumption about which questions it answers.",
    complicated: "App-mediated dating has accelerated the vocabulary collapse. Situationship, talking, hanging out, seeing each other — the proliferation of semi-terms signals a genuine cultural need for more precise relational vocabulary that the mainstream has not yet provided.",
    alsoSee: ["Romantic", "Situationship", "Commitment"]
  },
  {
    word: "Compersion",
    pos: "noun",
    pron: "kəmˈpɜːʃən",
    cat: "II",
    catLabel: "Experiential & Phenomenological",
    isNew: true,
    brief: "The pleasure you feel in your partner's pleasure with someone else. Frequently called the opposite of jealousy, which is not quite right but is close enough to be useful.",
    origins: "Coined in the Kerista commune in San Francisco in the 1970s–80s. The community needed a word for an experience that had no name in mainstream culture because mainstream culture did not validate the experience as possible.",
    practice: "Compersion is not the absence of jealousy — both can exist simultaneously. It is a distinct positive emotional response: the genuine pleasure of witnessing a partner's joy with another person. Monogamous couples occasionally experience it without a word for it.",
    complicated: "Compersion is sometimes presented in ENM spaces as an ideal to be achieved — something you should feel. Jealousy is not a character flaw; compersion is not an achievement. Both are emotional information.",
    alsoSee: ["Jealousy", "Polyamory", "Attachment"]
  },
  {
    word: "Basson's Model",
    pos: "proper noun",
    pron: "ˈbasənz ˈmɒdəl",
    cat: "V",
    catLabel: "Historical & Theoretical",
    isNew: false,
    brief: "The clinical framework that explains why many people's desire works nothing like the way they've been told it should — and why this is not a problem.",
    origins: "Developed by Canadian psychiatrist Rosemary Basson in a 2000 paper. Basson challenged the linear Masters & Johnson sexual response cycle by proposing that for many people, desire is often responsive rather than spontaneous — arising in the context of arousal rather than preceding it.",
    practice: "If you wait to feel desire before engaging in sexual activity, and your desire profile is responsive, you may be waiting for something that only arrives after you've already begun. This is not a failure of desire — it is a different architecture of desire.",
    complicated: "Basson's model has been widely adopted in sex therapy and is almost entirely unknown outside clinical contexts. The Masters & Johnson linear model remains the cultural default, meaning the majority of people with responsive desire patterns have received no framework that validates their experience.",
    alsoSee: ["Desire", "Spontaneous Desire", "Responsive Desire", "Masters & Johnson"]
  }
];
